#!/bin/bash
# iOS Flavors 配置脚本
# 此脚本帮助在 Xcode 项目中创建多 App 构建配置

set -e

echo "=========================================="
echo "  iOS 多 App 配置指南"
echo "=========================================="
echo ""
echo "请在 Xcode 中手动完成以下步骤："
echo ""
echo "1. 打开 ios/Runner.xcworkspace"
echo ""
echo "2. 创建 Build Configurations："
echo "   - 选择 Runner target → Info → Configurations"
echo "   - 点击 '+' 复制 Debug，命名为 'Prod-Debug'"
echo "   - 点击 '+' 复制 Release，命名为 'Prod-Release'"
echo "   - 点击 '+' 复制 Debug，命名为 'Beta-Debug'"
echo "   - 点击 '+' 复制 Release，命名为 'Beta-Release'"
echo ""
echo "3. 设置各 Configuration 的 xcconfig："
echo "   - Prod-Debug  → ios/Flutter/Prod.xcconfig"
echo "   - Prod-Release → ios/Flutter/Prod.xcconfig"
echo "   - Beta-Debug  → ios/Flutter/Beta.xcconfig"
echo "   - Beta-Release → ios/Flutter/Beta.xcconfig"
echo ""
echo "4. 验证 Scheme："
echo "   - 在 Xcode 顶部 Scheme 选择器中应能看到 'prod' 和 'beta'"
echo "   - 如果没有，点击 'Manage Schemes' 添加"
echo ""
echo "5. 为不同 App 设置不同图标（可选）："
echo "   - 在 Xcode 中右键 Runner → New Group"
echo "   - 创建 'Assets-Prod' 和 'Assets-Beta' 分组"
echo "   - 各自包含不同的 AppIcon"
echo ""
echo "=========================================="
echo "  配置完成后的使用方式"
echo "=========================================="
echo ""
echo "运行正式版：  flutter run --flavor prod --dart-define=FLAVOR=prod"
echo "运行体验版：  flutter run --flavor beta --dart-define=FLAVOR=beta"
echo "构建正式版：  flutter build ios --flavor prod --dart-define=FLAVOR=prod"
echo "构建体验版：  flutter build ios --flavor beta --dart-define=FLAVOR=beta"
echo ""
