name: storage
description: "Simple SharedPreferences storage wrapper package."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  service:
    path: ../service
  annotation:
    path: ../annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
