name: generator
description: "Code generator for service registration."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  build: ^2.4.0
  glob: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
